services:
    api:
        build:
            context: .docker/php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            app-network:
    nginx:
        image: nginx:1.25.3-alpine
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - "8000:8000"
            - "6001:6001"
        volumes:
            - ./:/var/www/html
            - .docker/nginx:/etc/nginx/conf.d
        networks:
            app-network:

    #Mysql service
    db:
        image: mysql:8.0
        environment:
            MYSQL_DB: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATA: /data/mysql
        volumes:
            - mysql-data:/data/mysql
        ports:
            - '3306:3306'
        networks:
            app-network:
        restart: unless-stopped

networks:
    app-network:

volumes:
    app-data:
    mysql-data: